language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

env:
  - RADIX_NO_EXT=0
  - RADIX_NO_EXT=1

matrix:
  exclude:
    - python: "pypy"  # pypy will always build without extension
      RADIX_NO_EXT=1

install:
  - python setup.py install

script:
  - python setup.py nosetests
