language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

env:
  - RADIX_NO_EXT=true
  - RADIX_NO_EXT=false

matrix:
  exclude:
    - python: "pypy"  # pypy will always build without extension
      env: RADIX_NO_EXT=false

install:
  - python setup.py install

script:
  - python setup.py nosetests
